name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:${GITHUB_SHA::8}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:${GITHUB_SHA::8}

    - name: Latest Tag
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:${GITHUB_SHA::8} ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:latest

    - name: Push Latest Tag
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:latest