name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Tag Docker Image
      run: |
        docker build . --file Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:${GITHUB_SHA::8} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:latest

    - name: List Docker Images
      run: docker images

    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:${GITHUB_SHA::8}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-githbdockerhb:latest
